remove console.logs, change necessary outputs -1 -> 0

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,14 +1,25 @@
 #!/usr/bin/env bash
 
-# Logging for bash script **************************************
+# Check that script is ran from root directory
+if [ $0 != "./run" ]
+then
+  echo "Please run this script from the root directory with ./run"
+  exit 1
+fi
+
+# Setup Logging for bash script **************************************
 LOG_LEVEL=${LOG_LEVEL:-0}
 LOG_FILE=${LOG_FILE:-"default.log"}
 
-if [ ! -f "$LOG_FILE" ]; then
-    touch "$LOG_FILE"
+if ! [[ "$LOG_LEVEL" =~ ^[0-2]$ ]]; then
+    echo "Error: Invalid LOG_LEVEL. Must be 0 (SILENT), 1 (INFO), or 2 (DEBUG). Defaulting to 0."
+    LOG_LEVEL=0
 fi
 
-# LL_SILENT=0
+if [ ! -f "$LOG_FILE" ]; then
+    touch "$LOG_FILE" || { echo "Error: Could not create log file $LOG_FILE."; exit 1; }
+fi
+
 LL_INFO=1
 LL_DEBUG=2
 
@@ -41,11 +52,12 @@ else
     # Check if dependencies are installed:
     if [ ! -d "node_modules" ]; then
         log $LL_INFO "Error: Dependencies are not installed. Run './run install' first"
+        echo "Error: Dependencies are not installed. Run './run install' first" >&2
         exit 1
     fi
 
     # run.js handles "test" and "<url_file>" commands
-    node dist/run.js "$@"
+    npx ts-node src/run.ts "$@"
     STATUS=$?
 
     exit $STATUS
